### ISSUE TITLE
GUI - Offline contactform

### ISSUE THREAD

**Issue by borgebjornar** [borgebjornar/APP2000-applikasjonsutvikling-21h-22v#3]
Fikse font osv så det er likt som på andre sider. Må også fjerne lenken contact. Fjerne ramme på contact boksen

**Comment by arcanumursi** [comment]
Må fikse mtp på footer.

**Comment by aass90** [comment]
footer skal nå være på plass selv når man zoomer. gjelder også for online contact, hvor også profilbilde følger siden.
